# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

jobs:
  build_1:
    machine: true

    working_directory: ~/Auto-Firmware-Dumper

    steps:
      - checkout
      - run:
          name: Setup Project
          command: |
              sudo apt-get update -y && sudo apt-get upgrade -y
              sudo apt-get install git wget curl cpio aria2 python3 neofetch tar gzip python3-pip -y
      - run:
          name: Setup Dumprx
          command: |
              git clone https://github.com/UntuKemeng/DumprX
              cd DumprX
              bash setup.sh
              pip3 install aospdtgen
              pip3 install twrpdtgen
              pip3 install dumpyara
              sudo pip3 install aospdtgen
              sudo pip3 install twrpdtgen
              sudo pip3 install dumpyara
      - run:
          name: dump firmware
          command: |
              cd DumprX
              git config --global user.name ${UN}
              git config --global user.email ${UEM}
              export TERM=xterm
              echo "${GTOKEN}" >> .github_token
              echo "${GIT_ORG}" >> .github_orgname
              echo "${TG_TOKEN}" >> .tg_token
              echo "${CHAT_ID}" >> .tg_chat
              bash dumper.sh ${FUR}

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_1:
          filters:
            tags:
              only: /.*/
