# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2

jobs:
  build_1:
    machine: true

    working_directory: ~/Auto-Firmware-Dumper

    steps:
      - checkout
      - run:
          name: update packages
          command: sudo apt-get update
      - run:
          name: install package
          command: sudo apt-get install git nano wget curl cpio aria2 python3 neofetch tar gzip python3-pip
      - run:
          name: installing github cli
          command: |
              (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
              && sudo mkdir -p -m 755 /etc/apt/keyrings \
              && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
              && cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
              && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
              && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
              && sudo apt update \
              && sudo apt install gh -y
      - run:
          name: setup dumprx
          command: |
              mkdir -p Auto-Dumper
              cd Auto-Dumper
              git clone https://github.com/UntuKemeng/DumprX
              cd DumprX
              bash setup.sh
              pip3 install aospdtgen
              pip3 install twrpdtgen
              pip3 install dumpyara
              sudo pip3 install aospdtgen
              sudo pip3 install twrpdtgen
              sudo pip3 install dumpyara
      - run:
          name: dump firmware
          command: |
              cd Auto-Dumper/DumprX
              export TERM=xterm
              bash dumper.sh ${FUR}
              chmod -R 777 out
      - run:
          name: Setting up Git
          command: |
              git config --global user.name ${UN}
              git config --global user.email ${UEM}
              git config --global http.postBuffer 524288000
              gh auth login --with-token <<< ${GTOKEN}
      - run:
          name: Uploading Dump
          command: bash sc/up

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_1:
          filters:
            tags:
              only: /.*/
