#!/usr/bin/env bash

ABATA="/home/circleci/Auto-Firmware-Dumper/"
cd ${ABATA}/Auto-Dumper
codename=$(cat codename.txt)
brand=$(cat brand.txt)
cd lineage-device-tree
dat=$(date +%Y%m%d)
git init
git branch -M lineage-${codename}-${dat}
git add . -f
git commit -s -m "${codename} : LineageOS compatible device tree"
gh repo create lineage_device_${brand}_${codename} --public --description="LineageOS compatible tree for $codename " --source=. --remote=origin --push
