#!/usr/bin/env bash

ABATA="/home/circleci/Auto-Firmware-Dumper/"
cd ${ABATA}/Auto-Dumper
codename=$(cat codename.txt)
brand=$(cat brand.txt)
version=$(cat version.txt)
cd twrp-device-tree/$brand/$codename
dat=$(date +%Y%m%d)
[ ! -f BoardConfig.mk ] && cd ${brand}/${codename}
git init
git branch -M twrp-${version}-${dat}
git add . -f
git commit -s -m "$codename : TWRP compatible device tree"
gh repo create twrp_device_${brand}_${codename} --public --description="TWRP compatible tree for $codename " --source=. --remote=origin --push
