#!/usr/bin/env bash

ABATA="/home/circleci/Auto-Firmware-Dumper/"
cd ${ABATA}/Auto-Dumper
codename=$(cat codename.txt)
brand=$(cat brand.txt)
cd vnd_project/android/vendor/${brand}/${codename}
chmod -R 777 *
dat=$(date +%Y%m%d)
git init
git branch -M vendor-${codename}-${dat}
git add . -f
git commit -s -m "${codename} : initial vendor tree"
gh repo create android_vendor_${brand}_${codename} --public --description="Vendor tree for $codename" --source=. --remote=origin --push
echo "Succesfull"
cd ${ABATA}/Auto-Dumper
rm -rf DumprX
rm -rf vnd_project
