name: Auto Firmware Dumper

on:
  workflow_dispatch:
    inputs:
      USER_NAME:
        description: 'Name in GitHub Account'
        required: true
        default: ''
      USER_EMAIL:
        description: 'E-mail in GitHub Account'
        required: true
        default: ''
      FIRMWARE_URL:
        description: 'Stock ROM Link'
        required: true
        default: ''

jobs:
  dump:
    name: Auto Firmware Dumper
    runs-on: ubuntu-latest
    env:
      FIRMWARE_URL: ${{ github.event.inputs.FIRMWARE_URL }}
      USER_NAME: ${{ github.event.inputs.USER_NAME }}
      USER_EMAIL: ${{ github.event.inputs.USER_EMAIL }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
      SSH_PUBKEY: ${{ secrets.SSH_PUBKEY }}
      KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      GITLAB_ORG: ${{ secrets.GIT_ORG }}
      TG_TOKEN: ${{ secrets.TG_TOKEN }}
      CHAT_ID: ${{ secrets.CHAT_ID }}
    permissions: write-all
    steps:
    - name: Check Out
      uses: actions/checkout@v4

    - name: Update Packages
      run: sudo apt -y install cpio aria2 git python3 neofetch tar gzip

    - name: Clone and Setup DumprX
      run: |
        mkdir -p Auto-Dumper && cd Auto-Dumper
        git clone https://github.com/DumprX/DumprX.git && cd DumprX
        bash setup.sh
        sudo echo "${SSH_KEY}" >> /root/.ssh/id_rsa
        sudo echo "${SSH_PUBKEY}" >> /root/.ssh/id_rsa.pub
        sudo echo "${KNOWN_HOSTS}" >> /root/.ssh/known_hosts

    - name: Creating Dump
      run: |
        cd ${GITHUB_WORKSPACE}/Auto-Dumper/DumprX
        echo "${GITLAB_TOKEN}" >> .gitlab_token
        echo "${GITLAB_ORG}" >> .gitlab_group
        echo "${TG_TOKEN}" >> .gitlab_token
        echo "${CHAT_ID}" >> .gitlab_group
        git config --global user.name "${USER_NAME}"
        git config --global user.email "${USER_EMAIL}"
        bash dumper.sh "${FIRMWARE_URL}"
