name: Auto Firmware Dumper

on:
  workflow_dispatch:
    inputs:
      USER_NAME:
        description: 'Name in GitHub Account'
        required: true
        default: ''
      USER_EMAIL:
        description: 'E-mail in GitHub Account'
        required: true
        default: ''
      FIRMWARE_URL:
        description: 'Stock ROM Link'
        required: true
        default: ''

jobs:
  dump:
    name: Auto Firmware Dumper
    runs-on: ubuntu-latest
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      PUSH_TO_GITLAB: true
    permissions: write-all
    steps:
    - name: Check Out
      uses: actions/checkout@v4

    - name: Update Packages
      run: sudo apt -y install cpio aria2 git python3 neofetch tar gzip

    - name: Clone and Setup DumprX
      run: |
        git clone https://github.com/DumprX/DumprX.git && cd DumprX
        bash setup.sh
        pip3 install pycryptodome

    - name: Add SSH key
      run: |
        mkdir -p /home/runner/.ssh
        echo "${{ secrets.SSH_KEY }}" > /home/runner/.ssh/id_rsa
        echo "${{ secrets.KNOWN_HOSTS }}" > /home/runner/.ssh/known_hosts
        chmod 600 /home/runner/.ssh/id_rsa
        chmod 600 /home/runner/.ssh/known_hosts
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null	
        ssh-add /home/runner/.ssh/id_rsa

    - name: Creating Dump
      run: |
        cd ${GITHUB_WORKSPACE}/DumprX
        echo "${{ secrets.GITLAB_TOKEN }}" > .gitlab_token
        echo "${{ secrets.GIT_ORG }}" > .gitlab_group
        echo "${{ secrets.TG_TOKEN }}" > .tg_token
        echo "${{ secrets.CHAT_ID }}" > .tg_chat
        git config --global user.name "${{ github.event.inputs.USER_NAME }}"
        git config --global user.email "${{ github.event.inputs.USER_EMAIL }}"
        bash dumper.sh "${{ github.event.inputs.FIRMWARE_URL }}"
